services:
  mariadb:
    image: mariadb:latest
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: password
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"

volumes:
  mariadb:
